{
    "type": "bundle",
    "id": "bundle--603ffd05-9a3c-44dd-9c64-a19013e7da74",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--d5a2f1c7-e075-4347-8347-e38df9d73407",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-07-13T00:06:05.518127Z",
            "modified": "2023-07-13T00:06:05.518127Z",
            "name": "CVE-2023-21250",
            "description": "In gatt_end_operation of gatt_utils.cc, there is a possible out of bounds write due to a missing bounds check. This could lead to remote code execution with no additional execution privileges needed. User interaction is not needed for exploitation.\n\n",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-21250"
                }
            ]
        }
    ]
}