{
    "type": "bundle",
    "id": "bundle--c74a2419-c564-4dfc-b233-6b0fbfaca522",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ea185a70-7c68-43fb-bd0d-21bf32df6891",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-01-19T00:17:09.937999Z",
            "modified": "2024-01-19T00:17:09.937999Z",
            "name": "CVE-2024-0654",
            "description": "A vulnerability, which was classified as problematic, was found in DeepFaceLab pretrained DF.wf.288res.384.92.72.22. Affected is an unknown function of the file mainscripts/Util.py. The manipulation leads to deserialization. Local access is required to approach this attack. The exploit has been disclosed to the public and may be used. VDB-251382 is the identifier assigned to this vulnerability.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-0654"
                }
            ]
        }
    ]
}