{
    "type": "bundle",
    "id": "bundle--c0258742-c526-48cc-b252-d581f0e6b787",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--189a54d4-5868-4313-bbd1-a1abe7920669",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-07-07T00:05:47.576685Z",
            "modified": "2023-07-07T00:05:47.576685Z",
            "name": "CVE-2023-37453",
            "description": "An issue was discovered in the USB subsystem in the Linux kernel through 6.4.2. There is an out-of-bounds and crash in read_descriptors in drivers/usb/core/sysfs.c.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-37453"
                }
            ]
        }
    ]
}