{
    "type": "bundle",
    "id": "bundle--0d443955-63df-4be5-8309-dd5b939acff3",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--fff01760-9f21-40e0-a20f-2618ec350afd",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-02-06T00:16:04.851082Z",
            "modified": "2024-02-06T00:16:04.851082Z",
            "name": "CVE-2023-50782",
            "description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-50782"
                }
            ]
        }
    ]
}